export const STATES = [
  {
    "no": 1,
    "state": "Alabama",
    "inc": 125,
    "llc": 115,
    "non_profit": 100,
  },
  {
    "no": 2,
    "state": "Alaska",
    "inc": 280,
    "llc": 280,
    "non_profit": 80,
  },
  {
    "no": 3,
    "state": "Arizona",
    "inc": 275,
    "llc": 265,
    "non_profit": 255,
  },
  {
    "no": 4,
    "state": "Arkansas",
    "inc": 80,
    "llc": 80,
    "non_profit": 80,
  },
  {
    "no": 5,
    "state": "California",
    "inc": 115,
    "llc": 85,
    "non_profit": 45,
  },
  {
    "no": 6,
    "state": "Colorado",
    "inc": 50,
    "llc": 50,
    "non_profit": 50,
  },
  {
    "no": 7,
    "state": "Connecticut",
    "inc": 270,
    "llc": 130,
    "non_profit": 135,
  },
  {
    "no": 8,
    "state": "D.C.",
    "inc": 89,
    "llc": 90,
    "non_profit": 89,
  },
  {
    "no": 9,
    "state": "Delaware",
    "inc": 185,
    "llc": 150,
    "non_profit": 100,
  },
  {
    "no": 10,
    "state": "Florida",
    "inc": 80,
    "llc": 135,
    "non_profit": 70,
  },
  {
    "no": 11,
    "state": "Georgia",
    "inc": 295,
    "llc": 230,
    "non_profit": 295,
  },
  {
    "no": 12,
    "state": "Hawaii",
    "inc": 105,
    "llc": 105,
    "non_profit": 80,
  },
  {
    "no": 13,
    "state": "Idaho",
    "inc": 150,
    "llc": 150,
    "non_profit": 80,
  },
  {
    "no": 14,
    "state": "Illinois",
    "inc": 305,
    "llc": 630,
    "non_profit": 105,
  },
  {
    "no": 15,
    "state": "Indiana",
    "inc": 120,
    "llc": 120,
    "non_profit": 60,
  },
  {
    "no": 16,
    "state": "Iowa",
    "inc": 80,
    "llc": 80,
    "non_profit": 50,
  },
  {
    "no": 17,
    "state": "Kansas",
    "inc": 120,
    "llc": 195,
    "non_profit": 50,
  },
  {
    "no": 18,
    "state": "Kentucky",
    "inc": 100,
    "llc": 120,
    "non_profit": 58,
  },
  {
    "no": 19,
    "state": "Louisiana",
    "inc": 180,
    "llc": 135,
    "non_profit": 180,
  },
  {
    "no": 20,
    "state": "Maine",
    "inc": 225,
    "llc": 250,
    "non_profit": 125,
  },
  {
    "no": 21,
    "state": "Maryland",
    "inc": 200,
    "llc": 180,
    "non_profit": 200,
  },
  {
    "no": 22,
    "state": "Massachusetts",
    "inc": 295,
    "llc": 520,
    "non_profit": 55,
  },
  {
    "no": 23,
    "state": "Michigan",
    "inc": 90,
    "llc": 90,
    "non_profit": 50,
  },
  {
    "no": 24,
    "state": "Minnesota",
    "inc": 185,
    "llc": 185,
    "non_profit": 120,
  },
  {
    "no": 25,
    "state": "Mississippi",
    "inc": 80,
    "llc": 80,
    "non_profit": 80,
  },
  {
    "no": 26,
    "state": "Missouri",
    "inc": 88,
    "llc": 135,
    "non_profit": 55,
  },
  {
    "no": 27,
    "state": "Montana",
    "inc": 120,
    "llc": 120,
    "non_profit": 70,
  },
  {
    "no": 28,
    "state": "Nebraska",
    "inc": 225,
    "llc": 295,
    "non_profit": 160,
  },
  {
    "no": 29,
    "state": "Nevada",
    "inc": 200,
    "llc": 200,
    "non_profit": 175,
  },
  {
    "no": 30,
    "state": "New Hampshire",
    "inc": 145,
    "llc": 145,
    "non_profit": 65,
  },
  {
    "no": 31,
    "state": "New Jersey",
    "inc": 140,
    "llc": 150,
    "non_profit": 90,
  },
  {
    "no": 32,
    "state": "New Mexico",
    "inc": 140,
    "llc": 90,
    "non_profit": 65,
  },
  {
    "no": 33,
    "state": "New York",
    "inc": 160,
    "llc": 225,
    "non_profit": 100,
  },
  {
    "no": 34,
    "state": "North Carolina",
    "inc": 255,
    "llc": 255,
    "non_profit": 190,
  },
  {
    "no": 35,
    "state": "North Dakota",
    "inc": 155,
    "llc": 155,
    "non_profit": 70,
  },
  {
    "no": 36,
    "state": "Ohio",
    "inc": 260,
    "llc": 260,
    "non_profit": 260,
  },
  {
    "no": 37,
    "state": "Oklahoma",
    "inc": 80,
    "llc": 130,
    "non_profit": 55,
  },
  {
    "no": 38,
    "state": "Oregan",
    "inc": 50,
    "llc": 70,
    "non_profit": 80,
  },
  {
    "no": 39,
    "state": "Pennsylvania",
    "inc": 275,
    "llc": 125,
    "non_profit": 275,
  },
  {
    "no": 40,
    "state": "Rhode Island",
    "inc": 260,
    "llc": 180,
    "non_profit": 65,
  },
  {
    "no": 41,
    "state": "South Carolina",
    "inc": 250,
    "llc": 110,
    "non_profit": 55,
  },
  {
    "no": 42,
    "state": "South Dakota",
    "inc": 175,
    "llc": 125,
    "non_profit": 75,
  },
  {
    "no": 43,
    "state": "Tennessee",
    "inc": 150,
    "llc": 330,
    "non_profit": 150,
  },
  {
    "no": 44,
    "state": "Texas",
    "inc": 325,
    "llc": 325,
    "non_profit": 50,
  },
  {
    "no": 45,
    "state": "Utah",
    "inc": 155,
    "llc": 155,
    "non_profit": 125,
  },
  {
    "no": 46,
    "state": "Vermont",
    "inc": 105,
    "llc": 105,
    "non_profit": 105,
  },
  {
    "no": 47,
    "state": "Virginia",
    "inc": 105,
    "llc": 130,
    "non_profit": 105,
  },
  {
    "no": 48,
    "state": "Washington",
    "inc": 225,
    "llc": 225,
    "non_profit": 80,
  },
  {
    "no": 49,
    "state": "West Virginia",
    "inc": 107,
    "llc": 130,
    "non_profit": 55,
  },
  {
    "no": 50,
    "state": "Wisconsin",
    "inc": 125,
    "llc": 160,
    "non_profit": 60,
  },
  {
    "no": 51,
    "state": "Wyoming",
    "inc": 130,
    "llc": 130,
    "non_profit": 55,
  },
]